### ISSUE TITLE
json_fwd.hpp broken since v3.11.0

### ISSUE THREAD

**Issue by insensiv-ah** [ArthurSonzogni/nlohmann_json_cmake_fetchcontent#14]
Since v3.11.0 the `json_fwd.hpp` contains an include of `nlohmann/detail/abi_macros.hpp` which is of course missing from this repo. As a result including `json_fwd.hpp` fails.

While the amalgamated `json_fwd.hpp` is missing from v3.11.0 and v3.11.1 in the original repo, there's one for v3.11.2 with the include correctly amalgamated: [nlohmann/json/.../json_fwd.hpp](https://github.com/nlohmann/json/blob/v3.11.2/single_include/nlohmann/json_fwd.hpp)

**Comment by ArthurSonzogni** [comment]
This repository is not more useful. Indeed, since v3.11.3, you can use:
```cmake
include(FetchContent)

FetchContent_Declare(json URL https://github.com/nlohmann/json/releases/download/v3.11.3/json.tar.xz)
FetchContent_MakeAvailable(json)

target_link_libraries(foo PRIVATE nlohmann_json::nlohmann_json)
```
directly.
