### ISSUE TITLE
Invalid fetch content link

### ISSUE THREAD

**Issue by Frago9876543210** [ArthurSonzogni/nlohmann_json_cmake_fetchcontent#3]
I accidentally noticed that the link for fetch content does not matches with repository name
![img1](https://user-images.githubusercontent.com/13465245/86596433-e07b3700-bfa2-11ea-8a6d-731117bcc18d.png)
maybe rename repo to more shorter name back?

**Comment by ArthurSonzogni** [comment]
Indeed! Thanks for reporting this!

**Comment by ArthurSonzogni** [comment]
Thanks! This is now fixed.
