### ISSUE TITLE
GitHub actions 60 days limitations

### ISSUE THREAD

**Issue by Frago9876543210** [ArthurSonzogni/nlohmann_json_cmake_fetchcontent#5]
https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/disabling-and-enabling-a-workflow

> Warning: To prevent unnecessary workflow runs, scheduled workflows may be disabled automatically. When a public repository is forked, scheduled workflows are disabled by default. In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days.

![image](https://user-images.githubusercontent.com/13465245/97105226-5b8b6900-16ca-11eb-9d70-e5ab95f72c10.png)

**Comment by ArthurSonzogni** [comment]
I think not other actions are needed on this repository, because it isn't forked.
Am I right?
